os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.16.1"
jdk:
  - oraclejdk8
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=10.16.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
install:
  -  install
script:
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
